# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('market', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('submitted', models.IntegerField()),
                ('buyOrSell', models.IntegerField()),
                ('paymentType', models.IntegerField()),
                ('senderSuffix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('balanceUsd', models.IntegerField()),
                ('balanceTr', models.IntegerField()),
                ('iban', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
